openapi: 3.0.3
info:
  title: FAA Airmen Certification REST Server
  description: |-
    A Spring boot REST server of the FAA Airmen Certification database.
  contact:
    email: nwfistere@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: FAA Airmen Certification database download
  url: https://www.faa.gov/licenses_certificates/airmen_certification/releasable_airmen_download
tags:
  - name: import
    description: Import data from FAA.
  - name: data-access
    description: Access imported data

paths:
  /pilots:
    get:
      tags:
        - data-access
      summary: Access pilot data
      operationId: getPilots
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PilotBasicModel'
  /pilot-certificates:
    get:
      tags:
        - data-access
      summary: Access pilot certificate data
      operationId: getPilotCertificates
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PilotCertModel'
  /non-pilots:
    get:
      tags:
        - data-access
      summary: Access non-pilot data
      operationId: getNonPilots
      responses:
        default:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NonPilotBasicModel'
  /non-pilot-certificates:
    get:
      tags:
        - data-access
      summary: Access non-pilot certificate data
      operationId: getNonPilotCertificates
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NonPilotCertModel'
  /import:
    post:
      tags:
        - import
      summary: Import FAA data
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Successfully started import.'
      operationId: postImport

components:
  schemas:
    CertModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1234
        uniqueId:
          type: string
          format: "[A-Z][0-9]{7}"
          example: A4456505
        firstName:
          type: string
        lastName:
          type: string
        type:
          type: string
        level:
          type: string
        expireDate:
          type: string
          format: "MMddyyyy"
          example: "11302020"
        ratings:
          type: array
          items:
            type: string
    BasicModel:
      type: object
      properties:
        uniqueId:
          type: string
          format: "[A-Z][0-9]{7}"
          example: A4456505
        firstName:
          type: string
        lastName:
          type: string
        street1:
          type: string
        street2:
          type: string
        city:
          type: string
        state:
          type: string
        zipCode:
          type: string
        country:
          type: string
        region:
          type: string
        medClass:
          type: string
        medDate:
          type: string
          format: "MMyyyy"
        medExpDate:
          type: string
          format: "MMyyyy"
        basicMedCourseDate:
          type: string
          format: "yyyyMMdd"
        basicMedCMECDate:
          type: string
          format: "yyyyMMdd"
    NonPilotBasicModel:
      allOf:
        - $ref: '#/components/schemas/BasicModel'
        - type: object
          properties:
            certificates:
              type: array
              items:
                $ref: '#/components/schemas/NonPilotCertModel'
    NonPilotCertModel:
      allOf:
        - $ref: '#/components/schemas/CertModel'
    PilotBasicModel:
      allOf:
        - $ref: '#/components/schemas/BasicModel'
        - type: object
          properties:
            certificates:
              type: array
              items:
                $ref: '#/components/schemas/PilotCertModel'
    PilotCertModel:
      allOf:
        - $ref: '#/components/schemas/CertModel'
        - type: object
          properties:
            typeRatings:
              type: array
              items:
                type: string